# taijitu/red/brain/report_generator.py
# Professional bug bounty report generator
# Converts scan findings into HackerOne-ready reports
# Includes CVSS scoring, impact assessment, PoC steps

import structlog
from datetime import datetime
from dataclasses import dataclass, field

log = structlog.get_logger()


@dataclass
class BugBountyReport:
    """Complete professional bug bounty report"""
    title: str
    severity: str
    cvss_score: float
    cvss_vector: str
    target: str
    vulnerability_type: str
    summary: str
    steps_to_reproduce: list
    impact: str
    remediation: str
    bounty_estimate: str
    timestamp: datetime
    raw_evidence: dict = field(default_factory=dict)


class ReportGenerator:
    """
    Professional bug bounty report generator

    Takes raw scan findings and produces:
    - HackerOne submission format
    - CVSS score calculation
    - Steps to reproduce
    - Impact assessment
    - Remediation guidance
    - Bounty estimate
    """

    def __init__(self):
        self.reports_generated = []
        log.info("report_generator_initialized")

    def generate_from_scan(
        self,
        scan_report: dict,
        target: str,
        program_name: str = "Bug Bounty Program",
    ) -> list:
        """
        Generate professional reports from scan results
        Returns list of BugBountyReport — one per finding
        """
        reports = []
        vulns = scan_report.get("vulnerabilities", {})

        for vuln_type, findings in vulns.items():
            for finding in findings:
                report = self._generate_single_report(
                    vuln_type=vuln_type,
                    finding=finding,
                    target=target,
                    program_name=program_name,
                )
                reports.append(report)
                self.reports_generated.append(report)

        log.info(
            "reports_generated",
            count=len(reports),
            target=target,
        )

        return reports

    def format_hackerone(self, report: BugBountyReport) -> str:
        """
        Format report for HackerOne submission
        Ready to copy-paste into HackerOne
        """
        steps = "\n".join(
            f"{i+1}. {step}"
            for i, step in enumerate(report.steps_to_reproduce)
        )

        return f"""# {report.title}

## Summary
{report.summary}

## Severity
**{report.severity.upper()}** — CVSS Score: {report.cvss_score}
CVSS Vector: `{report.cvss_vector}`

## Steps To Reproduce
{steps}

## Impact
{report.impact}

## Supporting Material / References
- Target: `{report.target}`
- Vulnerability Type: {report.vulnerability_type}
- Discovered: {report.timestamp.strftime('%Y-%m-%d')}
- Scanner: TAIJITU RED

## Remediation
{report.remediation}

---
*Report generated by TAIJITU RED — Authorized Security Testing*
"""

    def format_markdown(self, reports: list) -> str:
        """
        Format all reports as a single markdown document
        Good for internal documentation
        """
        if not reports:
            return "# No vulnerabilities found"

        lines = [
            "# TAIJITU RED — Vulnerability Report",
            f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
            f"Total findings: {len(reports)}",
            "",
            "---",
            "",
        ]

        # Group by severity
        for severity in ["critical", "high", "medium", "low"]:
            sev_reports = [
                r for r in reports
                if r.severity == severity
            ]
            if not sev_reports:
                continue

            lines.append(
                f"## {severity.upper()} ({len(sev_reports)} findings)"
            )
            lines.append("")

            for report in sev_reports:
                lines.append(f"### {report.title}")
                lines.append(f"**CVSS:** {report.cvss_score} | "
                            f"**Bounty:** {report.bounty_estimate}")
                lines.append("")
                lines.append(report.summary)
                lines.append("")
                lines.append("**Steps to reproduce:**")
                for i, step in enumerate(report.steps_to_reproduce):
                    lines.append(f"{i+1}. {step}")
                lines.append("")
                lines.append(f"**Impact:** {report.impact}")
                lines.append("")
                lines.append(f"**Fix:** {report.remediation}")
                lines.append("")
                lines.append("---")
                lines.append("")

        return "\n".join(lines)

    def _generate_single_report(
        self,
        vuln_type: str,
        finding: dict,
        target: str,
        program_name: str,
    ) -> BugBountyReport:
        """Generate a single professional report from a finding"""
        url = finding.get("url", target)
        param = finding.get("parameter", "unknown")
        payload = finding.get("payload", "")
        severity = finding.get("severity", "medium")
        evidence = finding.get("evidence", "")
        bounty = finding.get("bounty_estimate", "Unknown")

        # Generate CVSS score
        cvss_score, cvss_vector = self._calculate_cvss(
            vuln_type, severity
        )

        # Generate steps to reproduce
        steps = self._generate_steps(
            vuln_type, url, param, payload
        )

        # Generate impact statement
        impact = self._generate_impact(vuln_type, severity)

        # Generate remediation
        remediation = finding.get(
            "remediation",
            self._default_remediation(vuln_type),
        )

        return BugBountyReport(
            title=f"{vuln_type} in {url.split('?')[0].split('/')[-1]} via {param} parameter",
            severity=severity,
            cvss_score=cvss_score,
            cvss_vector=cvss_vector,
            target=url,
            vulnerability_type=vuln_type,
            summary=self._generate_summary(
                vuln_type, url, param, evidence
            ),
            steps_to_reproduce=steps,
            impact=impact,
            remediation=remediation,
            bounty_estimate=bounty,
            timestamp=datetime.utcnow(),
            raw_evidence=finding,
        )

    def _calculate_cvss(
        self,
        vuln_type: str,
        severity: str,
    ) -> tuple:
        """Calculate CVSS score and vector"""
        cvss_map = {
            "SQL Injection": (
                9.8,
                "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            ),
            "Reflected XSS": (
                6.1,
                "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            ),
            "Stored XSS": (
                8.2,
                "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:L/A:N",
            ),
            "SSRF": (
                9.1,
                "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
            ),
            "Path Traversal": (
                7.5,
                "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            ),
            "Open Redirect": (
                6.1,
                "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
            ),
        }

        default = (5.0, "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N")
        return cvss_map.get(vuln_type, default)

    def _generate_steps(
        self,
        vuln_type: str,
        url: str,
        param: str,
        payload: str,
    ) -> list:
        """Generate clear steps to reproduce"""
        base_url = url.split("?")[0]

        if vuln_type == "SQL Injection":
            return [
                f"Navigate to {url}",
                f"Identify the '{param}' parameter",
                f"Replace the parameter value with payload: {payload}",
                "Observe the SQL error in the response",
                "Confirm by trying: ' OR '1'='1 to bypass logic",
                "Use sqlmap to extract database: sqlmap -u \"{url}\" -p {param} --dbs",
            ]
        elif vuln_type == "Reflected XSS":
            return [
                f"Navigate to {url}",
                f"Identify the '{param}' parameter",
                f"Inject XSS payload: {payload}",
                "Observe the payload executing in the browser",
                "Confirm by checking page source for unencoded payload",
            ]
        elif vuln_type == "SSRF":
            return [
                f"Navigate to {url}",
                "Identify the URL parameter accepting external URLs",
                "Replace URL value with: http://169.254.169.254/latest/meta-data/",
                "Observe cloud metadata returned in response",
                "Escalate by reading IAM credentials from metadata",
            ]
        elif vuln_type == "Path Traversal":
            return [
                f"Navigate to {url}",
                f"Identify the '{param}' file parameter",
                f"Replace value with: ../../../etc/passwd",
                "Observe /etc/passwd contents in response",
                "Escalate by reading application config files",
            ]
        else:
            return [
                f"Navigate to {url}",
                f"Test the '{param}' parameter with payload: {payload}",
                "Observe the vulnerability in the response",
            ]

    def _generate_summary(
        self,
        vuln_type: str,
        url: str,
        param: str,
        evidence: str,
    ) -> str:
        """Generate professional summary paragraph"""
        summaries = {
            "SQL Injection": (
                f"A SQL injection vulnerability was identified in the '{param}' "
                f"parameter at {url}. The application fails to properly sanitize "
                f"user input before passing it to the database query, allowing an "
                f"attacker to manipulate the query logic. Evidence: {evidence}"
            ),
            "Reflected XSS": (
                f"A reflected cross-site scripting vulnerability was identified "
                f"in the '{param}' parameter at {url}. User-supplied input is "
                f"reflected in the response without proper encoding, allowing "
                f"an attacker to inject malicious scripts. Evidence: {evidence}"
            ),
            "SSRF": (
                f"A server-side request forgery vulnerability was identified at "
                f"{url}. The server can be forced to make requests to internal "
                f"services and cloud metadata endpoints, potentially exposing "
                f"credentials and internal infrastructure."
            ),
            "Path Traversal": (
                f"A path traversal vulnerability was identified in the '{param}' "
                f"parameter at {url}. The application does not properly validate "
                f"file paths, allowing an attacker to read arbitrary files from "
                f"the server filesystem. Evidence: {evidence}"
            ),
        }
        return summaries.get(
            vuln_type,
            f"{vuln_type} vulnerability found at {url} in {param} parameter. {evidence}",
        )

    def _generate_impact(self, vuln_type: str, severity: str) -> str:
        """Generate impact statement"""
        impacts = {
            "SQL Injection": (
                "An attacker can extract the entire database including user "
                "credentials, personal data, and sensitive business information. "
                "With write permissions, they can modify or delete data. "
                "In some configurations, SQL injection leads to remote code execution."
            ),
            "Reflected XSS": (
                "An attacker can steal session cookies to hijack authenticated "
                "user accounts, redirect users to phishing pages, perform actions "
                "on behalf of the victim, or deliver malware. Impact is highest "
                "when targeting admin users."
            ),
            "SSRF": (
                "An attacker can access internal services not exposed to the internet, "
                "read cloud instance metadata including IAM credentials, scan internal "
                "networks, and potentially achieve remote code execution through "
                "internal service exploitation."
            ),
            "Path Traversal": (
                "An attacker can read sensitive files including configuration files "
                "with database credentials, private keys, and application secrets. "
                "This often leads to full system compromise."
            ),
            "Open Redirect": (
                "An attacker can redirect users to malicious websites while "
                "appearing to come from a trusted domain, enabling phishing "
                "attacks and credential theft."
            ),
        }
        return impacts.get(
            vuln_type,
            f"This {severity} severity vulnerability could allow an attacker "
            f"to compromise the confidentiality, integrity, or availability "
            f"of the application or its data.",
        )

    def _default_remediation(self, vuln_type: str) -> str:
        """Default remediation for each vuln type"""
        remediations = {
            "SQL Injection": (
                "Use parameterized queries or prepared statements. "
                "Never concatenate user input into SQL queries. "
                "Implement a Web Application Firewall as a secondary control."
            ),
            "Reflected XSS": (
                "Encode all user-supplied data before reflecting it in HTML responses. "
                "Implement a Content Security Policy header. "
                "Use context-aware output encoding."
            ),
            "SSRF": (
                "Validate and allowlist URLs for any server-side requests. "
                "Block requests to private IP ranges and cloud metadata endpoints. "
                "Use a proxy with strict allowlisting for outbound requests."
            ),
            "Path Traversal": (
                "Validate file paths against an allowlist of permitted files. "
                "Use realpath() to resolve paths and verify they are within "
                "the expected directory. Never pass user input directly to "
                "file system functions."
            ),
        }
        return remediations.get(
            vuln_type,
            "Validate and sanitize all user input. "
            "Follow OWASP secure coding guidelines.",
        )


# ── GLOBAL INSTANCE ───────────────────────────────────
report_generator = ReportGenerator()